apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bot
  labels:
    app: bot
spec:
  serviceName: "kubernetes-bot"
  replicas: 2
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: giuliopime/k8s-bot:1.0.0
